### ISSUE TITLE
Add OpenSearch description

### ISSUE THREAD

**Issue by brainwo** [jeffcarp/chinesedict#34]
This helps adding search provider to a browser such as Mozilla Firefox, that can be used for search shortcut.

https://developer.mozilla.org/en-US/docs/Web/OpenSearch

**Comment by jeffcarp** [comment]
Done. Thanks for the feature request @brainwo! Can you verify?

**Comment by brainwo** [comment]
Yes, Firefox is able to pick it up. Thank you.
